package com.faisal.financecalc.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    val dashboard: String,
    val totalBalance: String,
    val income: String,
    val expenses: String,
    val debts: String,
    val shop: String,
    val profit: String,
    val settings: String,
    val appearance: String,
    val darkMode: String,
    val general: String,
    val currencySymbol: String,
    val language: String,
    val shopOverview: String,
    val inventoryValue: String,
    val inventoryItems: String,
    val buyPrice: String,
    val totalValue: String,
    val sellItem: String,
    val sellQuestion: String,
    val sellPrice: String,
    val profitLabel: String,
    val justDelete: String,
    val cancel: String,
    val sell: String,
    val newItem: String,
    val editItem: String,
    val name: String,
    val count: String,
    val quantity: String,
    val save: String,
    val chooseCurrency: String,
    val chooseLanguage: String,
    val home: String,
    // New Strings
    val welcomeBack: String,
    val changesToBalance: String,
    val history: String,
    val close: String,
    val previous: String,
    val newVal: String,
    val myCards: String,
    val addCard: String,
    val addNewCard: String,
    val cardHolder: String,
    val cardNumberLast4: String,
    val initialBalance: String,
    val colorStart: String,
    val colorEnd: String,
    val transactions: String,
    val newEntry: String,
    val editEntry: String,
    val placeholderExample: String,
    val totalAmountAuto: String,
    val amountLabel: String,
    val quickAdjust: String,
    val category: String,
    val excludeFromTotal: String,
    val excludeDescription: String,
    val splitBookingDetails: String,
    val addSubItem: String,
    val monthlyProfits: String,
    val monthLabel: String,
    val yearLabel: String,
    val sales: String,
    val addProfitManually: String,
    val descriptionName: String,
    val profitAmount: String,
    val monthRange: String,
    val suggestions: String,
    val delete: String,
    val logout: String,
    val auto: String,
    val itemsCount: String
)

val EnStrings = AppStrings(
    dashboard = "Dashboard",
    totalBalance = "Total Balance",
    income = "Income",
    expenses = "Expenses",
    debts = "Debts",
    shop = "Shop",
    profit = "Profit",
    settings = "Settings",
    appearance = "Appearance",
    darkMode = "Dark Mode",
    general = "General",
    currencySymbol = "Currency Symbol",
    language = "Language",
    shopOverview = "Shop Overview",
    inventoryValue = "Total Inventory Value (Buy Price)",
    inventoryItems = "Inventory Items",
    buyPrice = "Buy",
    totalValue = "Total Value",
    sellItem = "Sell Item",
    sellQuestion = "At what price did you sell",
    sellPrice = "Selling Price",
    profitLabel = "Profit",
    justDelete = "Just Delete",
    cancel = "Cancel",
    sell = "Sell",
    newItem = "New Item",
    editItem = "Edit Item",
    name = "Name",
    count = "Count",
    quantity = "Quantity",
    save = "Save",
    chooseCurrency = "Choose Currency",
    chooseLanguage = "Choose Language",
    home = "Home",
    // New Strings
    welcomeBack = "Welcome back,",
    changesToBalance = "Changes to your balance",
    history = "History",
    close = "Close",
    previous = "Previous",
    newVal = "New",
    myCards = "My Cards",
    addCard = "Add Card",
    addNewCard = "Add New Card",
    cardHolder = "Card Holder Name",
    cardNumberLast4 = "Card Number (Last 4 digits)",
    initialBalance = "Initial Balance",
    colorStart = "Color Start",
    colorEnd = "Color End",
    transactions = "Transactions",
    newEntry = "New Entry",
    editEntry = "Edit Entry",
    placeholderExample = "e.g. Starbucks",
    totalAmountAuto = "Total Amount (Auto)",
    amountLabel = "Amount",
    quickAdjust = "Quick Adjust",
    category = "Category",
    excludeFromTotal = "Exclude from Total",
    excludeDescription = "If checked, this will be highlighted gold and not counted.",
    splitBookingDetails = "Split Booking / Details",
    addSubItem = "Add Sub-Item",
    monthlyProfits = "Monthly Profits",
    monthLabel = "Month",
    yearLabel = "Year",
    sales = "Sales",
    addProfitManually = "Add Profit manually",
    descriptionName = "Description / Name",
    profitAmount = "Profit Amount",
    monthRange = "Month (1-12)",
    suggestions = "Suggestions:",
    delete = "Delete",
    logout = "Logout",
    auto = "(Auto)",
    itemsCount = "items"
)

val DeStrings = AppStrings(
    dashboard = "Übersicht",
    totalBalance = "Gesamtsaldo",
    income = "Einnahmen",
    expenses = "Ausgaben",
    debts = "Schulden",
    shop = "Laden",
    profit = "Gewinn",
    settings = "Einstellungen",
    appearance = "Erscheinungsbild",
    darkMode = "Dunkelmodus",
    general = "Allgemein",
    currencySymbol = "Währungssymbol",
    language = "Sprache",
    shopOverview = "Laden Übersicht",
    inventoryValue = "Gesamtwert Inventar (Einkauf)",
    inventoryItems = "Inventar Artikel",
    buyPrice = "Einkauf",
    totalValue = "Gesamtwert",
    sellItem = "Artikel verkaufen",
    sellQuestion = "Zu welchem Preis hast du verkauft",
    sellPrice = "Verkaufspreis",
    profitLabel = "Gewinn",
    justDelete = "Nur Löschen",
    cancel = "Abbrechen",
    sell = "Verkaufen",
    newItem = "Neuer Artikel",
    editItem = "Artikel bearbeiten",
    name = "Name",
    count = "Anzahl",
    quantity = "Menge",
    save = "Speichern",
    chooseCurrency = "Währung wählen",
    chooseLanguage = "Sprache wählen",
    home = "Startseite",
    // New Strings
    welcomeBack = "Willkommen zurück,",
    changesToBalance = "Änderungen am Guthaben",
    history = "Verlauf",
    close = "Schließen",
    previous = "Vorher",
    newVal = "Neu",
    myCards = "Meine Karten",
    addCard = "Karte hinzufügen",
    addNewCard = "Neue Karte hinzufügen",
    cardHolder = "Karteninhaber",
    cardNumberLast4 = "Kartennummer (letzte 4)",
    initialBalance = "Anfangssaldo",
    colorStart = "Farbe Start",
    colorEnd = "Farbe Ende",
    transactions = "Transaktionen",
    newEntry = "Neuer Eintrag",
    editEntry = "Eintrag bearbeiten",
    placeholderExample = "z.B. Starbucks",
    totalAmountAuto = "Gesamtbetrag (Auto)",
    amountLabel = "Betrag",
    quickAdjust = "Schnell anpassen",
    category = "Kategorie",
    excludeFromTotal = "Von Summe ausschließen",
    excludeDescription = "Wenn aktiviert, wird dies gold markiert und nicht gezählt.",
    splitBookingDetails = "Aufteilung / Details",
    addSubItem = "Unterpunkt hinzufügen",
    monthlyProfits = "Monatliche Gewinne",
    monthLabel = "Monat",
    yearLabel = "Jahr",
    sales = "Verkäufe",
    addProfitManually = "Gewinn manuell hinzufügen",
    descriptionName = "Beschreibung / Name",
    profitAmount = "Gewinnbetrag",
    monthRange = "Monat (1-12)",
    suggestions = "Vorschläge:",
    delete = "Löschen",
    logout = "Abmelden",
    auto = "(Auto)",
    itemsCount = "Artikel"
)

val ArStrings = AppStrings(
    dashboard = "لوحة التحكم",
    totalBalance = "إجمالي الرصيد",
    income = "الدخل",
    expenses = "المصروفات",
    debts = "الديون",
    shop = "المتجر",
    profit = "الأرباح",
    settings = "الإعدادات",
    appearance = "المظهر",
    darkMode = "الوضع الداكن",
    general = "عام",
    currencySymbol = "رمز العملة",
    language = "الغة",
    shopOverview = "نظرة عامة على المتجر",
    inventoryValue = "قيمة المخزون (شراء)",
    inventoryItems = "عناصر المخزون",
    buyPrice = "شراء",
    totalValue = "القيمة الإجمالية",
    sellItem = "بيع عنصر",
    sellQuestion = "بكم بعت",
    sellPrice = "سعر البيع",
    profitLabel = "الربح",
    justDelete = "حذف فقط",
    cancel = "إلغاء",
    sell = "بيع",
    newItem = "عنصر جديد",
    editItem = "تعديل عنصر",
    name = "الاسم",
    count = "العدد",
    quantity = "الكمية",
    save = "حفظ",
    chooseCurrency = "اختر العملة",
    chooseLanguage = "اختر اللغة",
    home = "الرئيسية",
    // New Strings
    welcomeBack = "مرحبًا بعودتك،",
    changesToBalance = "تغييرات الرصيد",
    history = "السجل",
    close = "إغلاق",
    previous = "السابق",
    newVal = "الجديد",
    myCards = "بطاقاتي",
    addCard = "إضافة بطاقة",
    addNewCard = "إضافة بطاقة جديدة",
    cardHolder = "اسم حامل البطاقة",
    cardNumberLast4 = "رقم البطاقة (آخر 4)",
    initialBalance = "الرصيد الأولي",
    colorStart = "لون البداية",
    colorEnd = "لون النهاية",
    transactions = "المعاملات",
    newEntry = "إدخال جديد",
    editEntry = "تعديل الإدخال",
    placeholderExample = "مثال: ستاربكس",
    totalAmountAuto = "الإجمالي (تلقائي)",
    amountLabel = "المبلغ",
    quickAdjust = "تعديل سريع",
    category = "الفئة",
    excludeFromTotal = "استبعاد من الإجمالي",
    excludeDescription = "إذا تم تحديده، سيتم التمييز باللون الذهبي ولن يتم احتسابه.",
    splitBookingDetails = "تقسيم الحجز / التفاصيل",
    addSubItem = "إضافة عنصر فرعي",
    monthlyProfits = "الأرباح الشهرية",
    monthLabel = "الشهر",
    yearLabel = "السنة",
    sales = "المبيعات",
    addProfitManually = "إضافة ربح يدويًا",
    descriptionName = "الوصف / الاسم",
    profitAmount = "مبلغ الربح",
    monthRange = "الشهر (1-12)",
    suggestions = "اقتراحات:",
    delete = "حذف",
    logout = "تسجيل خروج",
    auto = "(تلقائي)",
    itemsCount = "عناصر"
)

val FrStrings = AppStrings(
    dashboard = "Tableau de bord",
    totalBalance = "Solde total",
    income = "Revenus",
    expenses = "Dépenses",
    debts = "Dettes",
    shop = "Boutique",
    profit = "Profit",
    settings = "Paramètres",
    appearance = "Apparence",
    darkMode = "Mode sombre",
    general = "Général",
    currencySymbol = "Symbole monétaire",
    language = "Langue",
    shopOverview = "Aperçu de la boutique",
    inventoryValue = "Valeur totale (Achat)",
    inventoryItems = "Articles en stock",
    buyPrice = "Achat",
    totalValue = "Valeur totale",
    sellItem = "Vendre l'article",
    sellQuestion = "À quel prix avez-vous vendu",
    sellPrice = "Prix de vente",
    profitLabel = "Profit",
    justDelete = "Supprimer seulement",
    cancel = "Annuler",
    sell = "Vendre",
    newItem = "Nouvel article",
    editItem = "Modifier l'article",
    name = "Nom",
    count = "Nombre",
    quantity = "Quantité",
    save = "Enregistrer",
    chooseCurrency = "Choisir la devise",
    chooseLanguage = "Choisir la langue",
    home = "Accueil",
    // New Strings
    welcomeBack = "Bon retour,",
    changesToBalance = "Modifications du solde",
    history = "Historique",
    close = "Fermer",
    previous = "Précédent",
    newVal = "Nouveau",
    myCards = "Mes cartes",
    addCard = "Ajouter une carte",
    addNewCard = "Ajouter une nouvelle carte",
    cardHolder = "Nom du titulaire",
    cardNumberLast4 = "Numéro de carte (4 derniers)",
    initialBalance = "Solde initial",
    colorStart = "Couleur début",
    colorEnd = "Couleur fin",
    transactions = "Transactions",
    newEntry = "Nouvelle entrée",
    editEntry = "Modifier l'entrée",
    placeholderExample = "ex. Starbucks",
    totalAmountAuto = "Montant total (Auto)",
    amountLabel = "Montant",
    quickAdjust = "Ajustement rapide",
    category = "Catégorie",
    excludeFromTotal = "Exclure du total",
    excludeDescription = "Si coché, sera surligné en or et non compté.",
    splitBookingDetails = "Détails de la répartition",
    addSubItem = "Ajouter un sous-élément",
    monthlyProfits = "Profits mensuels",
    monthLabel = "Mois",
    yearLabel = "Année",
    sales = "Ventes",
    addProfitManually = "Ajouter un profit manuellement",
    descriptionName = "Description / Nom",
    profitAmount = "Montant du profit",
    monthRange = "Mois (1-12)",
    suggestions = "Suggestions :",
    delete = "Supprimer",
    logout = "Déconnexion",
    auto = "(Auto)",
    itemsCount = "articles"
)

val LocalAppStrings = staticCompositionLocalOf { DeStrings }
