package com.faisal.financecalc.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    val dashboard: String,
    val totalBalance: String,
    val income: String,
    val expenses: String,
    val debts: String,
    val shop: String,
    val profit: String,
    val settings: String,
    val appearance: String,
    val darkMode: String,
    val general: String,
    val currencySymbol: String,
    val language: String,
    val shopOverview: String,
    val inventoryValue: String,
    val inventoryItems: String,
    val buyPrice: String,
    val totalValue: String,
    val sellItem: String,
    val sellQuestion: String,
    val sellPrice: String,
    val profitLabel: String,
    val justDelete: String,
    val cancel: String,
    val sell: String,
    val newItem: String,
    val editItem: String,
    val name: String,
    val count: String,
    val quantity: String,
    val save: String, // Speichern
    val chooseCurrency: String,
    val chooseLanguage: String,
    val home: String
)

val EnStrings = AppStrings(
    dashboard = "Dashboard",
    totalBalance = "Total Balance",
    income = "Income",
    expenses = "Expenses",
    debts = "Debts",
    shop = "Shop",
    profit = "Profit",
    settings = "Settings",
    appearance = "Appearance",
    darkMode = "Dark Mode",
    general = "General",
    currencySymbol = "Currency Symbol",
    language = "Language",
    shopOverview = "Shop Overview",
    inventoryValue = "Total Inventory Value (Buy Price)",
    inventoryItems = "Inventory Items",
    buyPrice = "Buy",
    totalValue = "Total Value",
    sellItem = "Sell Item",
    sellQuestion = "At what price did you sell",
    sellPrice = "Selling Price",
    profitLabel = "Profit",
    justDelete = "Just Delete",
    cancel = "Cancel",
    sell = "Sell",
    newItem = "New Item",
    editItem = "Edit Item",
    name = "Name",
    count = "Count",
    quantity = "Quantity",
    save = "Save",
    chooseCurrency = "Choose Currency",
    chooseLanguage = "Choose Language",
    home = "Home"
)

val DeStrings = AppStrings(
    dashboard = "Übersicht",
    totalBalance = "Gesamtsaldo",
    income = "Einnahmen",
    expenses = "Ausgaben",
    debts = "Schulden",
    shop = "Laden",
    profit = "Gewinn",
    settings = "Einstellungen",
    appearance = "Erscheinungsbild",
    darkMode = "Dunkelmodus",
    general = "Allgemein",
    currencySymbol = "Währungssymbol",
    language = "Sprache",
    shopOverview = "Laden Übersicht",
    inventoryValue = "Gesamtwert Inventar (Einkauf)",
    inventoryItems = "Inventar Artikel",
    buyPrice = "Einkauf",
    totalValue = "Gesamtwert",
    sellItem = "Artikel verkaufen",
    sellQuestion = "Zu welchem Preis hast du verkauft",
    sellPrice = "Verkaufspreis",
    profitLabel = "Gewinn",
    justDelete = "Nur Löschen",
    cancel = "Abbrechen",
    sell = "Verkaufen",
    newItem = "Neuer Artikel",
    editItem = "Artikel bearbeiten",
    name = "Name",
    count = "Anzahl",
    quantity = "Menge",
    save = "Speichern",
    chooseCurrency = "Währung wählen",
    chooseLanguage = "Sprache wählen",
    home = "Startseite"
)

val ArStrings = AppStrings(
    dashboard = "لوحة التحكم",
    totalBalance = "إجمالي الرصيد",
    income = "الدخل",
    expenses = "المصروفات",
    debts = "الديون",
    shop = "المتجر",
    profit = "الأرباح",
    settings = "الإعدادات",
    appearance = "المظهر",
    darkMode = "الوضع الداكن",
    general = "عام",
    currencySymbol = "رمز العملة",
    language = "الغة",
    shopOverview = "نظرة عامة على المتجر",
    inventoryValue = "قيمة المخزون (شراء)",
    inventoryItems = "عناصر المخزون",
    buyPrice = "شراء",
    totalValue = "القيمة الإجمالية",
    sellItem = "بيع عنصر",
    sellQuestion = "بكم بعت",
    sellPrice = "سعر البيع",
    profitLabel = "الربح",
    justDelete = "حذف فقط",
    cancel = "إلغاء",
    sell = "بيع",
    newItem = "عنصر جديد",
    editItem = "تعديل عنصر",
    name = "الاسم",
    count = "العدد",
    quantity = "الكمية",
    save = "حفظ",
    chooseCurrency = "اختر العملة",
    chooseLanguage = "اختر اللغة",
    home = "الرئيسية"
)

val FrStrings = AppStrings(
    dashboard = "Tableau de bord",
    totalBalance = "Solde total",
    income = "Revenus",
    expenses = "Dépenses",
    debts = "Dettes",
    shop = "Boutique",
    profit = "Profit",
    settings = "Paramètres",
    appearance = "Apparence",
    darkMode = "Mode sombre",
    general = "Général",
    currencySymbol = "Symbole monétaire",
    language = "Langue",
    shopOverview = "Aperçu de la boutique",
    inventoryValue = "Valeur totale (Achat)",
    inventoryItems = "Articles en stock",
    buyPrice = "Achat",
    totalValue = "Valeur totale",
    sellItem = "Vendre l'article",
    sellQuestion = "À quel prix avez-vous vendu",
    sellPrice = "Prix de vente",
    profitLabel = "Profit",
    justDelete = "Supprimer seulement",
    cancel = "Annuler",
    sell = "Vendre",
    newItem = "Nouvel article",
    editItem = "Modifier l'article",
    name = "Nom",
    count = "Nombre",
    quantity = "Quantité",
    save = "Enregistrer",
    chooseCurrency = "Choisir la devise",
    chooseLanguage = "Choisir la langue",
    home = "Accueil"
)

val LocalAppStrings = staticCompositionLocalOf { DeStrings }
